name: Hello world workflow

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test-001
      PROJECT_ID: hutest-345118
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@v0
        with:
         service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
         project_id: ${{env.PROJECT_ID}}
         export_default_credentials: true
      
      - name: Build docker image
        run: docker build . -t asia.gcr.io/hutest-345118/hashtest:latest
      
      - name: Configure docker client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker image to container 
        env: 
         GIT_TAG: v0.1.0
        run: 
          # docker tag builtimage:v1 asia.gcr.io/hutest-345118/hashtest:latest
          docker push asia.gcr.io/hutest-345118/hashtest:latest
      
      - name : Deploy on gcp
        run : gcloud run deploy hashtest --quiet --image asia.gcr.io/hutest-345118/hashtest:latest --platform managed --region asia-south1
          

         
 
